### ISSUE TITLE
"Project not found: 'my-app@dev'"

### ISSUE THREAD

**Issue by gregbenner** [alan345/naperg#5]
Sorry if this is something I'm missing but I think I have everything setup.
The 3 processes and the docker. I can navigate to http://localhost:4466/my-app/dev in the browser
but when I try to create a user  `Project not found: 'my-app@dev`
Maybe I'm missing something but it looks like it can't find the graphql server?

`http://localhost:4466/my-app/dev
Type "Node" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Server is running on http://localhost:4000
Error: Not authorized
    at getUserId (/Users/gnb/Sites/naperg/server/src/utils.js:14:11)
    at me (/Users/gnb/Sites/naperg/server/src/resolvers/auth.js:17:14)
    at resolveFieldValueOrError (/Users/gnb/Sites/naperg/server/node_modules/graphql/execution/execute.js:531:18)
    at resolveField (/Users/gnb/Sites/naperg/server/node_modules/graphql/execution/execute.js:495:16)
    at /Users/gnb/Sites/naperg/server/node_modules/graphql/execution/execute.js:364:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/gnb/Sites/naperg/server/node_modules/graphql/execution/execute.js:361:42)
    at executeOperation (/Users/gnb/Sites/naperg/server/node_modules/graphql/execution/execute.js:289:122)
    at executeImpl (/Users/gnb/Sites/naperg/server/node_modules/graphql/execution/execute.js:154:14)
    at Object.execute (/Users/gnb/Sites/naperg/server/node_modules/graphql/execution/execute.js:131:229)
Request to http://localhost:4466/my-app/dev:
query:
query ($_v0_where: PostWhereInput) {
  posts(where: $_v0_where) {
    id
    text
    title
    isPublished
    nameFile
    __typename
  }
}
operationName: null
variables:
{
  "_v0_where": {
    "isPublished": true
  }
}
[GraphQL error]: Message: Project not found: 'my-app@dev', Location: undefined, Path: undefined
[Network error]: Error: Project not found: 'my-app@dev'
Error: Project not found: 'my-app@dev'
    at BatchedGraphQLClient.<anonymous> (/Users/gnb/Sites/naperg/server/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:69:35)
    at step (/Users/gnb/Sites/naperg/server/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/Users/gnb/Sites/naperg/server/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/Users/gnb/Sites/naperg/server/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at process._tickCallback (internal/process/next_tick.js:178:7)`

**Comment by alan345** [comment]
Hi thanks for your feedback. 
I have edited readme file.
Try: 
3/ In folder `/server`, run:
* `docker-compose up -d` init app
* `prisma deploy` Deploy app

**Comment by gregbenner** [comment]
Thanks so much! Works perfectly
